version: "3.8"

services:
  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"
    volumes:
      - ./observability/mimir/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/data

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
      - mimir
      - tempo

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "4318:4318"
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "/etc/alloy/config.alloy",
      ]
    depends_on:
      - loki
      - mimir
      - tempo

  api-gateway:
    image:
    environment:
    ports:
      - "8000:8000"
    depends_on:
      - alloy

  user-service:
    image:
    environment:
    ports:
      - "8002:8002"
    depends_on:
      - alloy

  notification-service:
    image:
    environment:
    ports:
      - "8001:8001"
    depends_on:
      - alloy

volumes:
  loki-data:
  mimir-data:
  tempo-data:
