version: "3.8"

services:
  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"
    volumes:
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/data

  loki:
    image: grafana/loki:latest
    user: "0"
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki

  tempo:
    image: grafana/tempo:2.4.2
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-pyroscope-app,grafana-exploretraces-app,grafana-metricsdrilldown-app
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=trinhquanglam2k4@gmail.com
      - GF_SMTP_PASSWORD=mahtsqzkuilojhwx
      - GF_SMTP_FROM_ADDRESS=trinhquanglam2k4@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alert

    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - mimir
      - tempo

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "4318:4318"
      - "3101:3100"
    volumes:
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "/etc/alloy/config.alloy",
      ]
    depends_on:
      - loki
      - mimir
      - tempo
    user: root

  api-gateway:
    build:
      context: ./app/api-gateway
      args:
        PORT: 8000
    environment:
      - NODE_ENV=production
      - NOTIFICATION_SERVICE_HOST=http://notification-service:8001
      - USER_SERVICE_HOST=http://user-service:8002
      - USER_SERVICE_BASE_API=/api/users
      - NOTIFICATION_SERVICE_BASE_API=/api/notifications
    ports:
      - "8000:8000"
    depends_on:
      - alloy

  user-service:
    build:
      context: ./app/user-service
      args:
        PORT: 8002
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://vunhankien:vunhankien@cluster0.s6pbtkn.mongodb.net/topic
      - NOTIFICATION_SERVICE_HOST=http://notification-service:8001
      - NOTIFICATION_SERVICE_BASE_API=/api/notifications
    ports:
      - "8002:8002"
    depends_on:
      - alloy

  notification-service:
    build:
      context: ./app/notification-service
      args:
        PORT: 8001
    environment:
      - NODE_ENV=production
      - EMAIL_USER=vnkien28082004@gmail.com
      - EMAIL_PASS=pccjqzddmebadlvb
    ports:
      - "8001:8001"
    depends_on:
      - alloy

volumes:
  grafana-data:
  loki-data:
  mimir-data:
  tempo-data:
