apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100

  - name: Mimir
    type: prometheus
    uid: mimir
    url: http://mimir:9009/prometheus
    isDefault: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "anonymous"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
